#' Take data and format it for user
#'
#' This function either takes the results of a primary run of `parse_raw_data`,
#' or the name of a file containing data from that run, and processes it. The idea
#' is that it either provides a report of all processing steps for user intervention,
#' or it takes the results of user intervention and reports a summary that can be used
#' for other things, like for example actual downstream applications, who'd have guessed it.
#'
#' @param data either a data.frame of data from `parse_raw_data`, or the name of a file
#' generated by a run of `parse_raw_data`
#' @param output.prefix character vector, prefix for any output files generated by the function
#' @param create.summary.data logical, whether to provide a simplified summary result for
#' reporting final data by category
#' @export
process.output <- function(data, output.prefix, create.summary.data = TRUE) {
	result.df <- NA
	if (is.data.frame(data)) {
		result.df <- data
	} else if (is.vector(data, mode = "character")) {
		stopifnot(file.exists(data))
		result.df <- read.table(data, header = TRUE, sep = "\t",, quote = "", stringsAsFactors = FALSE)
	} else {
		stop("unrecognized data format in function 'process.output'")
	}
	stopifnot(is.vector(output.prefix, mode = "character"))
	stopifnot(is.logical(create.summary.data))
	if (create.summary.data) {
		## compute some mild summary data for function
		print("collapsing data into final report format")
		final.df <- data.frame(Category = c(), Vote = c(), Title = c(), Author = c(), Count = c())
		for (category in unique(result.df$category)) {
			category.df <- result.df[result.df[, "category"] == category, ]
			category.df <- category.df[!is.na(category.df[, "final.title"]) &
									   !is.na(category.df[, "final.author"]), ]
			category.vote <- paste(category.df$final.title, category.df$final.author, sep = " by ")
			category.table <- as.data.frame(table(category.vote))
			category.table <- category.table[order(category.table[, 2], decreasing = TRUE), ]
			category.df <- data.frame(Category = category,
									  Vote = category.table[, 1],
									  Title = gsub("^(.*) by (.*)$", "\\1", category.table[, 1], perl = TRUE),
									  Author = gsub("^(.*) by (.*)$", "\\2", category.table[, 1], perl = TRUE),
									  Count = category.table[, 2])
			final.df <- rbind(final.df, category.df)
		}
		write.table(final.df, paste(output.prefix, ".final-results.tsv", sep = ""), row.names = FALSE, col.names = TRUE, quote = FALSE, sep = "\t")
	} else {
		write.table(result.df, paste(output.prefix, ".tsv", sep = ""), row.names=FALSE, col.names=TRUE, quote=FALSE, sep="\t")
	}
}